// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storehouse.proto

package web.pb;

public interface StorehouseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorehouseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
