server:
  port: 9090

spring:
  application:
    name: gateway-proxy
  main:
    web-application-type: reactive
#  cloud:
#    gateway:
#      global-cors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders:
#              - "*"
#      routes:
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#          filters:
#            - RewritePath=/store/(?<segment>.*), /order/${segment}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true


