server:
  port: 0

spring:
  application:
    name: delivery-service
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      order: order-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preference-ip-address: true