// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storehouse.proto

package web.pb;

public interface StorehouseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorehouseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isHas = 1;</code>
   * @return The isHas.
   */
  boolean getIsHas();
}
